version: '3.8'

services:
  mlflow:
    image: python:3.10-slim
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir mlflow==2.16.0 && \
             mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db \
             --default-artifact-root /mlflow/artifacts \
             --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow
    restart: unless-stopped

volumes:
  mlflow_data:


